{% set name = "pytest-github-actions-annotate-failures" %}
{% set version = "0.1.2" %}

# TODO:
# - version >0.1.0 (unreleased) includes LICENSE in sdist, remove from feedstock

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-github-actions-annotate-failures-{{ version }}.tar.gz
  sha256: 9eb6ee2943ecde2078fe620af7dbf32646c0267f538435cd805fe2e8d735ca3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pytest >=4.0.0
    - python

test:
  imports:
    - pytest_github_actions_annotate_failures
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/utgwkk/pytest-github-actions-annotate-failures
  summary: pytest plugin to annotate failed tests with a workflow command for GitHub Actions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
