{% set version = "0.3.0" %}

package:
  name: pytest-github-actions-annotate-failures
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-github-actions-annotate-failures/pytest_github_actions_annotate_failures-{{ version }}.tar.gz
  sha256: d4c3177c98046c3900a7f8ddebb22ea54b9f6822201b5d3ab8fcdea51e010db7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64.0.0
    - setuptools_scm >=7.0.5
  run:
    - pytest >=6.0.0
    - python >={{ python_min }}

test:
  imports:
    - pytest_github_actions_annotate_failures
  commands:
    - pip list
    - pip list > pip-listed.txt
    - grep -iE "pytest-github-actions-annotate-failures\s+{{ version.replace(".", "\.") }}" pip-listed.txt
    - python -m pip check
  requires:
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}

about:
  home: https://github.com/pytest-dev/pytest-github-actions-annotate-failures
  summary: pytest plugin to annotate failed tests with a workflow command for GitHub Actions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
